nav:
  - Home: 'index.md'
  - Custom Bee Data : 'bee_data/custom_bee_data.md'
  - Breed Data : 'bee_data/breed_data.md'
  - Centrifuge Data : 'bee_data/centrifuge_data.md'
  - Combat Data : 'bee_data/combat_data.md'
  - Mutation Data : 'bee_data/mutation_data.md'
  - Spawn Data : 'bee_data/spawn_data.md'
  - Trait Data : 'bee_data/trait_data.md'

site_name: Resourceful Bees Docs
docs_dir: docs
theme: readthedocs

extra:
  current_version: 1.16.3
  versions:
    1.16.3: 1.16.3
    1.15: 1.15
