nav:
  - Home: 'index.md'
  - Color Data : 'data/color_data.md'

site_name: Resourceful Bees Docs
docs_dir: docs
theme: readthedocs

extra:
  current_version: 1.15
  versions:
    1.15: 1.15
    1.16.3: 1.16.3